In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [2]:
banco = pd.read_csv("C:/Users/glria/Documents/Análisis_datos/Proyectos/Proyecto4_Gloria/EDA_Python_GloriaMartin/Archivos/bank-additional.csv")
banco.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [3]:
banco.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: float64(7), int64(5), str(12)
memory usage: 7.9 MB

In [4]:
banco.duplicated().sum()

np.int64(0)

In [5]:
banco['job'].unique()

<StringArray>
[    'housemaid',      'services',        'admin.',   'blue-collar',
    'technician',       'retired',    'management',    'unemployed',
 'self-employed',             nan,  'entrepreneur',       'student']
Length: 12, dtype: str

In [6]:
banco['contact'].unique()

<StringArray>
['telephone', 'cellular']
Length: 2, dtype: str

In [7]:
banco['poutcome'].unique()

<StringArray>
['NONEXISTENT', 'FAILURE', 'SUCCESS']
Length: 3, dtype: str

In [8]:
banco1 = banco.copy()

In [9]:
import locale
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

'es_ES.UTF-8'

In [10]:
banco1['date'] = pd.to_datetime(banco1["date"], format='%d-%B-%Y')
banco1.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [11]:
banco1['contact_year'] = banco1['date'].dt.year
banco1.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,contact_year
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,2019.0
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,2016.0
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,2019.0
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,2015.0
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,2017.0

In [12]:
banco1['contact_month'] = banco1['date'].dt.month
banco1.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,contact_year,contact_month
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,2019.0,8.0
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,2016.0,9.0
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,2019.0,2.0
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,2015.0,11.0
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,2017.0,1.0

In [13]:
banco1['contact_month'] = banco1['contact_month'].fillna(0).astype(int)
banco1['contact_year'] = banco1['contact_year'].fillna(0).astype(int)
banco1.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,contact_year,contact_month
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,2019,8
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,2016,9
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,2019,2
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,2015,11
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,2017,1

In [14]:
banco1['contact_year'].unique()

array([2019, 2016, 2015, 2017, 2018,    0])

In [15]:
banco1 = banco1.rename(columns={'id_':'ID'})
banco1.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,ID,contact_year,contact_month
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,2019,8
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,2016,9
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,2019,2
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,2015,11
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,2017,1

In [16]:
banco1.set_index(['ID'], inplace = True)
banco1.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,contact_year,contact_month
ID,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,41.495,-71.233,2019,8
e9d37224-cb6f-4942-98d7-46672963d097,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,34.601,-83.923,2016,9
3f9f49b5-e410-4948-bf6e-f9244f04918b,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,34.939,-94.847,2019,2
9991fafb-4447-451a-8be2-b0df6098d13e,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,49.041,-70.308,2015,11
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,38.033,-104.463,2017,1

In [17]:
banco1.drop('Unnamed: 0', axis=1, inplace=True)
banco1.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,contact_year,contact_month
ID,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,41.495,-71.233,2019,8
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,34.601,-83.923,2016,9
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,34.939,-94.847,2019,2
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,49.041,-70.308,2015,11
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,38.033,-104.463,2017,1

In [18]:
banco1.drop('latitude', axis=1, inplace=True)
banco1.drop('longitude', axis=1, inplace=True)
banco1.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,contact_year,contact_month
ID,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,2019,8
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,2016,9
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,2019,2
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,2015,11
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,2017,1

In [19]:
banco1 = banco1.rename(columns={'y':'product'})
banco1.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,product,date,contact_year,contact_month
ID,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,2019,8
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,2016,9
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,2019,2
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,2015,11
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,2017,1

In [20]:
banco1['default'] = banco1['default'].apply(lambda x: 'yes' if x == 1 else 'no')
banco1.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,product,date,contact_year,contact_month
ID,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,no,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,2019,8
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,no,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,2016,9
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,no,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,2019,2
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,no,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,2015,11
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,no,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,2017,1

In [21]:
banco1['housing'] = banco1['housing'].apply(lambda x: 'yes' if x == 1 else 'no')
banco1.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,product,date,contact_year,contact_month
ID,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,no,no,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,2019,8
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,no,no,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,2016,9
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,no,yes,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,2019,2
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,no,no,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,2015,11
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,no,no,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,2017,1

In [22]:
banco1['loan'] = banco1['loan'].apply(lambda x: 'yes' if x == 1 else 'no')
banco1.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,product,date,contact_year,contact_month
ID,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,no,no,no,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,2019,8
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,no,no,no,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,2016,9
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,no,yes,no,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,2019,2
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,no,no,no,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,2015,11
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,no,no,yes,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,2017,1

In [23]:
clientes_2012 = pd.read_excel("C:/Users/glria/Documents/Análisis_datos/Proyectos/Proyecto4_Gloria/EDA_Python_GloriaMartin/Archivos/customer-details.xlsx", sheet_name=0)
clientes_2012.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [24]:
clientes_2012_1 = clientes_2012.copy()

In [25]:
clientes_2012_1.set_index(['ID'], inplace = True)
clientes_2012_1.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
ID,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,0,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,1,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,2,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,3,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,4,63164,1,2,2012-06-20,20

In [26]:
clientes_2012_1.drop('Unnamed: 0', axis=1, inplace=True)
clientes_2012_1.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
ID,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20,20

In [27]:
clientes_2013 = pd.read_excel("C:/Users/glria/Documents/Análisis_datos/Proyectos/Proyecto4_Gloria/EDA_Python_GloriaMartin/Archivos/customer-details.xlsx", sheet_name=1)
clientes_2013.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479
2,2,78839,1,0,2013-11-25,21,9cb15c53-b647-464a-add9-09cdae04897c
3,3,113859,1,1,2013-01-06,12,f8aaf334-949d-4943-a214-b64fe9c088b4
4,4,147317,0,0,2013-07-10,14,885fe85a-3718-4760-a32a-a57628cf7528

In [28]:
clientes_2013_1 = clientes_2013.copy()

In [29]:
clientes_2013_1.set_index(['ID'], inplace = True)
clientes_2013_1.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
ID,,,,,,
ef81336c-e41a-46d0-8a30-5d4ac3b836be,0,82407,0,1,2013-10-07,29
50b224ac-84b4-42a7-aba9-3e1d1d620479,1,24877,0,0,2013-04-21,32
9cb15c53-b647-464a-add9-09cdae04897c,2,78839,1,0,2013-11-25,21
f8aaf334-949d-4943-a214-b64fe9c088b4,3,113859,1,1,2013-01-06,12
885fe85a-3718-4760-a32a-a57628cf7528,4,147317,0,0,2013-07-10,14

In [30]:
clientes_2013_1.drop('Unnamed: 0', axis=1, inplace=True)
clientes_2013_1.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
ID,,,,,
ef81336c-e41a-46d0-8a30-5d4ac3b836be,82407,0,1,2013-10-07,29
50b224ac-84b4-42a7-aba9-3e1d1d620479,24877,0,0,2013-04-21,32
9cb15c53-b647-464a-add9-09cdae04897c,78839,1,0,2013-11-25,21
f8aaf334-949d-4943-a214-b64fe9c088b4,113859,1,1,2013-01-06,12
885fe85a-3718-4760-a32a-a57628cf7528,147317,0,0,2013-07-10,14

In [31]:
clientes_2014 = pd.read_excel("C:/Users/glria/Documents/Análisis_datos/Proyectos/Proyecto4_Gloria/EDA_Python_GloriaMartin/Archivos/customer-details.xlsx", sheet_name=2)
clientes_2014.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,168812,1,1,2014-06-10,27,4d6c811c-0f24-4a73-b374-2ebd1f80d46e
1,1,108615,2,1,2014-04-05,24,eef0f24f-cbdb-4c67-b371-09d7bc59695e
2,2,179041,0,2,2014-09-22,4,bbfdcedd-199d-4927-94bb-5dad051ff471
3,3,116639,2,2,2014-08-16,3,e8ebb67d-4ee1-4615-b701-eefe3af607eb
4,4,49537,0,1,2014-09-05,28,f7f79ace-0024-4505-a401-f340946f0942

In [32]:
clientes_2014_1 = clientes_2014.copy()

In [33]:
clientes_2014_1.set_index(['ID'], inplace = True)
clientes_2014_1.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
ID,,,,,,
4d6c811c-0f24-4a73-b374-2ebd1f80d46e,0,168812,1,1,2014-06-10,27
eef0f24f-cbdb-4c67-b371-09d7bc59695e,1,108615,2,1,2014-04-05,24
bbfdcedd-199d-4927-94bb-5dad051ff471,2,179041,0,2,2014-09-22,4
e8ebb67d-4ee1-4615-b701-eefe3af607eb,3,116639,2,2,2014-08-16,3
f7f79ace-0024-4505-a401-f340946f0942,4,49537,0,1,2014-09-05,28

In [34]:
clientes_2014_1.drop('Unnamed: 0', axis=1, inplace=True)
clientes_2014_1.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
ID,,,,,
4d6c811c-0f24-4a73-b374-2ebd1f80d46e,168812,1,1,2014-06-10,27
eef0f24f-cbdb-4c67-b371-09d7bc59695e,108615,2,1,2014-04-05,24
bbfdcedd-199d-4927-94bb-5dad051ff471,179041,0,2,2014-09-22,4
e8ebb67d-4ee1-4615-b701-eefe3af607eb,116639,2,2,2014-08-16,3
f7f79ace-0024-4505-a401-f340946f0942,49537,0,1,2014-09-05,28

In [35]:
clientes_concat = pd.concat([clientes_2012_1, clientes_2013_1, clientes_2014_1], axis = 0)
clientes_concat

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
ID,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20,20
...,...,...,...,...,...
5f432048-d515-4bb5-9c94-62db451f88d4,156980,1,2,2014-05-17,7
993bbbd6-4dbc-4a40-a408-f91f8462bee6,139820,0,0,2014-09-29,1
d6271666-319d-42c8-a741-cb22bf2c2093,78470,2,2,2014-10-28,12
f67fbfa8-6573-414d-a805-b26a2f1b1ceb,144218,0,1,2014-07-01,9
9727bc06-c11a-461a-a5bb-3d210467cc2a,115155,0,2,2014-12-25,7

In [36]:
banco_clientes = banco1.join(clientes_concat, how='inner')
banco_clientes.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,product,date,contact_year,contact_month,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,no,no,no,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,2019,8,161770,1,0,2012-04-04,29
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,no,no,no,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,2016,9,85477,1,1,2012-12-30,7
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,no,yes,no,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,2019,2,147233,1,1,2012-02-02,5
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,no,no,no,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,2015,11,121393,1,2,2012-12-21,29
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,no,no,yes,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,2017,1,63164,1,2,2012-06-20,20

In [37]:
banco_clientes.info()

<class 'pandas.DataFrame'>
Index: 43000 entries, 089b39d8-e4d0-461b-87d4-814d71e0e079 to 993bbbd6-4dbc-4a40-a408-f91f8462bee6
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                37880 non-null  float64
 1   job                42655 non-null  str
 2   marital            42915 non-null  str
 3   education          41193 non-null  str
 4   default            43000 non-null  str
 5   housing            43000 non-null  str
 6   loan               43000 non-null  str
 7   contact            43000 non-null  str
 8   duration           43000 non-null  int64
 9   campaign           43000 non-null  int64
 10  pdays              43000 non-null  int64
 11  previous           43000 non-null  int64
 12  poutcome           43000 non-null  str
 13  emp.var.rate       43000 non-null  float64
 14  cons.price.idx     42529 non-null  str
 15  cons.conf.idx      43000 non-null  str
 16  euribor3m          33744 non-null  str
 17  nr.employed        43000 non-null  str
 18  product            43000 non-null  str
 19  date               42752 non-null  datetime64[us]
 20  contact_year       43000 non-null  int64
 21  contact_month      43000 non-null  int64
 22  Income             43000 non-null  int64
 23  Kidhome            43000 non-null  int64
 24  Teenhome           43000 non-null  int64
 25  Dt_Customer        43000 non-null  datetime64[us]
 26  NumWebVisitsMonth  43000 non-null  int64
dtypes: datetime64[us](2), float64(2), int64(10), str(13)
memory usage: 9.2+ MB

DATOS PERSONALES CLIENTES

In [41]:
edad_media = banco_clientes['age'].mean()
print(edad_media)

39.97711193241816

In [53]:
trabajos = banco_clientes.groupby('job').size()
print(trabajos)

job
admin.           10873
blue-collar       9654
entrepreneur      1522
housemaid         1123
management        3050
retired           1790
self-employed     1489
services          4162
student            903
technician        7026
unemployed        1063
dtype: int64

In [43]:
casados_solteros = banco_clientes.groupby('marital').size()
print(casados_solteros)

marital
DIVORCED     4811
MARRIED     25999
SINGLE      12105
dtype: int64

In [44]:
nivel_educativo = banco_clientes.groupby('education').size()
print(nivel_educativo)

education
basic.4y                4356
basic.6y                2386
basic.9y                6309
high.school             9925
illiterate                18
professional.course     5477
university.degree      12722
dtype: int64

In [47]:
ingresos_calculos = banco_clientes['Income'].agg(['mean', 'max', 'min', 'median'])
print(ingresos_calculos)

mean       93241.20007
max       180802.00000
min         5841.00000
median     93050.50000
Name: Income, dtype: float64

In [50]:
niños = banco_clientes.groupby('Kidhome').size()
print(niños)

Kidhome
0    14210
1    14374
2    14416
dtype: int64

In [51]:
adolescentes = banco_clientes.groupby('Teenhome').size()
print(adolescentes)

Teenhome
0    14345
1    14370
2    14285
dtype: int64

In [52]:
media_visitas_web = banco_clientes['NumWebVisitsMonth'].mean()
print(media_visitas_web)

16.589697674418606

DATOS BANCARIOS CLIENTES